### ISSUE TITLE
Prepare and release 0.7.0

### ISSUE THREAD

**Issue by chalin** [google/docsy-example#222]
For known issues with [Docsy 0.7.0], see:

- https://github.com/google/docsy/issues/1568

### Tasks

- [x] Mention **known issues** with [Docsy 0.7.0] in the release comment, and link to the issue given above
- [x] Drop warning at the start of the README (#224)
- [x] Docsy user guide: Add to the clone command `--depth 1 --branch v0.7.0`, so that version `v.7.0` is cloned (see corresponding [pull request](https://github.com/google/docsy/pull/1577)).

[Docsy 0.7.0]: https://github.com/google/docsy/releases/tag/v0.7.0

**Comment by chalin** [comment]
@geriom - might you be available to submit a PR for this in case @deining isn't available?

**Comment by deining** [comment]
All three tasks are completed, closing this issue.

**Comment by chalin** [comment]
Great thanks!
