### ISSUE TITLE
Display Persian (`fa`) pages in right-to-left (RTL) fashion & other improvements

### ISSUE THREAD

**Issue by chalin** [google/docsy-example#295]
- [x] google/docsy-example#294
- [x] google/docsy-example#300
- [x] google/docsy-example#302
- [x] #304
- [x] #305 - brings in RTL support for projects using Docsy via Hugo modules
- [x] #322
- [x] #325
- [x] google/docsy#2019
- [ ] Upgrade Docsy
